### ISSUE TITLE
list_packages seems to be breaking?

### ISSUE THREAD

**Issue by Ironholds** [metacran/crandb#34]
> data <- list_packages(limit = 1000)
Error in robust_q(service, url, fun, args, servers, odds, timeout_multiplier = timeout_multiplier *  : 
  Cannot do query '/-/desc?start_key=""&limit=1000'.

**Comment by gaborcsardi** [comment]
Yeah, you hit a timeout. Use the direct JSON API, see the README.

**Comment by gaborcsardi** [comment]
I.e. just get `http://crandb.r-pkg.org/-/desc` directly.

**Comment by Ironholds** [comment]
*thumbs up*

**Comment by gaborcsardi** [comment]
It is still a bug, but in the R package. :)

**Comment by gaborcsardi** [comment]
This seems to be working fine, at least with the devel version of the `spareserver` package (to be submitted to CRAN soon).
