### ISSUE TITLE
Help me understand the "releases"?

### ISSUE THREAD

**Issue by jennybc** [metacran/crandb#35]
I'm looking at the number of releases in the ~6500 packages on CRAN around the end of April. There's a huge number with 0 releases (see attached figure). I don't think this is real or right, yes? For example `dplyr` is one of those packages. Can you help me figure out what I'm looking at? BTW I computed number of releases from the length of the `releases` vector. We are getting this info through the API but below I just use `crandb`.

```
> library(crandb)
> package("dplyr")$releases
Argument unicode has been deprecated. YAJL always parses unicode.
list()
> package("lattice")$releases
Argument unicode has been deprecated. YAJL always parses unicode.
list()
> package("grid")$releases
Argument unicode has been deprecated. YAJL always parses unicode.
 [1] "2.0.0"  "2.0.1"  "2.1.0"  "2.1.1"  "2.2.0"  "2.2.1"  "2.3.0"  "2.3.1" 
 [9] "2.4.0"  "2.4.1"  "2.5.0"  "2.5.1"  "2.6.0"  "2.6.1"  "2.6.2"  "2.7.0" 
[17] "2.7.1"  "2.7.2"  "2.8.0"  "2.8.1"  "2.9.0"  "2.9.1"  "2.9.2"  "2.10.0"
[25] "2.10.1" "2.11.0" "2.11.1" "2.12.0" "2.12.1" "2.12.2" "2.13.0" "2.13.1"
[33] "2.13.2" "2.14.0" "2.14.1" "2.14.2" "2.15.0" "2.15.1" "2.15.2" "2.15.3"
[41] "3.0.0"  "3.0.1" 
```

![n_rel](https://cloud.githubusercontent.com/assets/599454/7992961/c45a43ea-0ab7-11e5-9406-d2b1ba9a461b.png)

@ironholds @dgrtwo

**Comment by gaborcsardi** [comment]
A package version is included in a release if it was current at the time when that R version was released. As if CRAN was snapshotted at the time of the R release. 

The only problem is that recent releases are missing, because I essentially gave up on the idea. Without any support from CRAN, it is too error-prone. You can see that 3.1.1 is the last "release". 

So the reasons for the many packages without any releases are:
- their most recent version was released after 3.1.1, and 
- possibly errors.

The majority is the former, I guess. 

If you want, I can add 3.1.2, 3.1.3 and 3.2.0, but the packages that were published after 3.2.0 will still have no release.

**Comment by jennybc** [comment]
Ooohhh. I completely didn't understand this field.

So when I look at a page like this:

http://cran.r-project.org/src/contrib/Archive/lattice/

or this:

https://github.com/cran/lattice/releases

and see the release history … that's not systematically exposed in this API?

Do you have any suggestions for obtaining that info? Given the above, I can think of various web-scrapy hacks / usage of the GitHub API but wonder if you have any thoughts on the matter.

**Comment by gaborcsardi** [comment]
See e.g. http://crandb.r-pkg.org/dplyr/all and search for `timeline`. Or from the command line:

```r
crandb::package("dplyr", version = "all")
#> ...
#> Other versions: 0.4.0, 0.3.0.2, 0.3.0.1, 0.3, 0.2, 0.1.3, 0.1.2, 0.1.1,
#>   0.1
```

**Comment by jennybc** [comment]
Got it. Thanks. I can re-download the metadata we're getting from your API to get *all* versions (sadly, not our current default).

**Comment by gaborcsardi** [comment]
You can just get `http://crandb.r-pkg.org/-/allall?limit=5` without the limit, and that will give you everything.

**Comment by jennybc** [comment]
OK that worked! And only took several seconds actually. This should keep me busy :).

**Comment by jennybc** [comment]
For posterity, wanna correct the url? `http://crandb.r-pkg.org/-/all` (you've got two "all"s above).

**Comment by gaborcsardi** [comment]
Sorry removed that URL, because I don't want robots to hit on it, it is heavy on the site. The `allall` is not a mistake, it also includes `archived` packages: https://github.com/metacran/crandb#-allall-complete-records-for-all-packages-including-archived-ones

Not the best name, I agree.....

**Comment by jennybc** [comment]
OK got it. Sorry and thanks again.
