### ISSUE TITLE
Error if not using the exact version format the package authors specified in DESCRIPTION

### ISSUE THREAD

**Issue by bearloga** [metacran/crandb#38]
Works:

```R
> package("devtools", "0.6")
CRAN package devtools 0.6, 4 years ago
Title: Tools to make developing R code easier
...
```

Doesn't:

```R
> package("devtools", "0.6.0")
Error: crandb query: 
```

Would be great if the system could match that properly.

**Comment by gaborcsardi** [comment]
Well, in R `0.6` is not the same as `0.6.0`, in fact `0.6 < 0.6.0` holds:

```r
> compareVersion("0.6", "0.6.0")
[1] -1
```
So I am not sure what I can do here.

**Comment by bearloga** [comment]
Really?! Oh wow, that seems...odd. Okay, nevermind then. Thanks!

**Comment by bearloga** [comment]
Although…

```R
> numeric_version("0.6") == numeric_version("0.6.0")
[1] TRUE
```

But I don't know if that matters.

**Comment by gaborcsardi** [comment]
Interesting, this is messed up. 

Btw., it would be somewhat hard for me to implement.
