### ISSUE TITLE
consider adding timeout_multiplier or ... to functions that call spare_q

### ISSUE THREAD

**Issue by restonslacker** [metacran/crandb#40]
A minor nit but it takes close to 2 minutes for list_packages() to fail if the servers can't be pinged. Perhaps I'm just impatient, but it would be nice to be able to short that.

**Comment by gaborcsardi** [comment]
Honestly, I think I'll just drop spareserver. It is hard to get it right.

**Comment by restonslacker** [comment]
Ok.  Thanks for all of your efforts on this and within the r community in general!
