### ISSUE TITLE
any chance of a maintainers route?

### ISSUE THREAD

**Issue by sckott** [metacran/crandb#45]
to query maintainers by email, immediate use case is for the cran checks API.  I need to move away from Ruby to command line scripts for scraping check pages, and I haven't found a fast CLI way to parse https://cloud.r-project.org/web/checks/check_summary_by_maintainer.html to pull out maintainer email addresses

**Comment by gaborcsardi** [comment]
http://crandb.r-pkg.org/-/maintainernames?group_level=2&limit=5
http://crandb.r-pkg.org/-/maintainer?keys=[%22myrmecocystus@gmail.com%22]

Full API here:
https://github.com/metacran/crandb/blob/master/inst/app.js#L46

**Comment by sckott** [comment]
ha! didn't see that, thanks. that should help me speed up the scraping
