### ISSUE TITLE
releases() vs rversions

### ISSUE THREAD

**Issue by maelle** [metacran/crandb#47]
Is `releases()` (and the corresponding endpoint of the API) still useful given that `rversions` exists?

**Comment by gaborcsardi** [comment]
that's a different thing

**Comment by maelle** [comment]
can you explain why?

**Comment by gaborcsardi** [comment]
the crandb one is for this: https://github.com/metacran/crandb#-releasepkgsversion-packages-that-were-current-at-an-r-release

but it has not been updated for a while

**Comment by maelle** [comment]
I'm confused because the README states "The releases() function lists recent R versions, with their release dates."

**Comment by gaborcsardi** [comment]
yes, but the main deal is the end point I linked

**Comment by maelle** [comment]
Ok now I got it, thanks!
